### ISSUE TITLE
Schematics not readable for everyone

### ISSUE THREAD

**Issue by Teufelchen1** [Ryzee119/OpenXenium#18]
Hi! 🙋‍♀️ 
Hope your are alright, haven't read you a long time!

I wonder if you could provide the schematics in a more accessible format? Currently it is only provided in a non-free, highly specialised file format. I would love to see some `*.svg` or `*.pdf`. 

Typed with love,
Teufelchen

**Comment by Ryzee119** [comment]
Not sure I understand exactly. PDF is here:
https://github.com/Ryzee119/OpenXenium/releases

Eagle .sch files also viewable by the free version of Autodesk Eagle.

**Comment by Teufelchen1** [comment]
Oh thanks, I just looked inside the repo, not the releases. 😅
You might consider adding the PDF to the repo as `OpenXenium/Hardware/Xenium2019.pdf`(or similar), to ease the next one searching for it.

**Comment by Ryzee119** [comment]
Ive added a link in the Hardware readme that points to the releases page where the PDF is located. Hopefully that will help anyone in the future looking for it :)

https://github.com/Ryzee119/OpenXenium/blob/master/Hardware/README.md
