### ISSUE TITLE
Xenium Blue 

### ISSUE THREAD

**Issue by Huawei85** [Ryzee119/OpenXenium#20]
Hi.
      It is a very interesting Project. I have a issue with my Xenium chip it is a Xenium blue chip 
My xbox is V1.4 with winbond Bios chip and Focus Video Decoder chip. My xbox is tsoped with xecuter 2 vga bios. I have a Xenium blue chip my xbox didn't detect it. I tried hot swap and direct install method but it didn't detect it. BTW Xenium tools 1.1 and 1.0 works on my Xbox without any modchip. I didn't have jtag programmer. Is there any way to program CPLD without JTAG? I have tried everything else. Can you help me?

Thanks in Advance.

**Comment by Ryzee119** [comment]
If you made this chip yourself you need to program the cpld before xeniumtools will detect it.

You can program the CPLD with a raspi too

**Comment by Huawei85** [comment]
No I don't made it it was in my xbox and it is not working

**Comment by Huawei85** [comment]
Hi can you give me a compiled XSVF Firmware file for cpld?

**Comment by Ernegien** [comment]
You should be able to use this which is a slightly modified version (extra feature you won't use) of what's currently on master.

[openxenium-lpc-peripheral-support.zip](https://github.com/Ryzee119/OpenXenium/files/7093962/openxenium-lpc-peripheral-support.zip)
