### ISSUE TITLE
S29AL016J70TFI02  Not working

### ISSUE THREAD

**Issue by TheRealNextria** [Ryzee119/OpenXenium#24]
Hello Ryzee119.

Got a lot of S29AL016J70TFI02 chips, but it does not seem to work with the openxenium.
I use a programmer on my pc to program the chips, this always works with the S29AL016J70TFI01 chips.

But now on the S29AL016J70TFI02, it boots (sometimes), will take a while too load the menu, but when booting a bios.
it will hang, and it looks like the chip is empty.(after desoldering the chip again and dumping it)

Is there a way to make openxenium work with the S29AL016J70TFI02   ?

Regards,

Nextria

**Comment by Ryzee119** [comment]
That's not a supported chip. `02` indicates bottom boot sector. We need top bootsector device.

The only way to get this working is to rewrite XeniumOS.
