### ISSUE TITLE
Program XeniumOS without need for modchipped Xbox 

### ISSUE THREAD

**Issue by VoxelTek** [Ryzee119/OpenXenium#26]
Hi there,

Is it possible to have a way of programming XeniumOS to the OpenXenium without needing a modchipped Xbox? I want to build one myself from scratch, given that I don't have a modchip and modchip prices are greater than I would like. Building one from scratch would be cheaper, however, impossible if I cannot program XeniumOS onto it without having a modchipped Xbox.

Would it be possible to program the software onto it using something such as an Arduino or Pi Pico?

Kind regards,

VoxelTek

**Comment by Ryzee119** [comment]
You have to program the CPLD and the flash chip. These both use common programming methods and can be done anyway you can find.

Here's an example using a rasp pi which first programs the CPLD as a bridge to program the flash chip, then writes the OX firmware to the CPLD. Although it has a full PCB you can wire it up manually.
https://github.com/kooscode/xenium-programmer

**Comment by VoxelTek** [comment]
Ah, neat. I didn't know of this. Your guide seemed to imply that the only way to program the flash was using a modded Xbox, but it's nice to know that there's an alternative that's more readily available.

I do really appreciate the existence of this modchip, and I'm looking forward to creating one myself!
