### ISSUE TITLE
Pcbway issue

### ISSUE THREAD

**Issue by DecanFrost** [Ryzee119/OpenXenium#27]
![W539954AS2D1](https://user-images.githubusercontent.com/26047042/230817347-f9fd4362-1a6e-4c89-9124-1e505e66c4a8.png)

Pcbway says they can not proceed due to an issue with soldermask *(see pic)

Subject: PCBWay- EQ of order W539954AS2D1_OpenXenium-ddff195-gerbers
 
Hi,
There is a engineering question of order W539954AS2D1.
As shown, the spacing between IC pad is only 0.12mm, we can not do the solder mask bridge.
Please check is it ok to do whole opening for this area?

Any suggestions

Thank you

**Comment by Ryzee119** [comment]
This is a pcbway limitation not a board issue really. Dont need solder mask there i guess; just makes it harder to solder
