### ISSUE TITLE
iMPACT project file missing.

### ISSUE THREAD

**Issue by kooscode** [Ryzee119/OpenXenium#8]
When you implement the Top Module and clicking on Tools >> iMPACT, it complains that there is no iMPACT project file.

I guess you would need to create a new iMPACT project by using a JTAG boundary scan?

**Comment by Ryzee119** [comment]
I believe you're right. It has been a while.
If you have worked it out and you think it would be worthwhile adding a step in https://github.com/Ryzee119/OpenXenium/tree/master/Firmware please raise a Pull Request with the change :)

**Comment by Ryzee119** [comment]
I've updated the programming instructions to explain how to generate the impact project file.
